### ISSUE TITLE
react native support

### ISSUE THREAD

**Issue by sibelius** [guigrpa/jest-html#1]
Awesome idea!

How can we improve this package to work better with react native?

Maybe using https://github.com/necolas/react-native-web to render the snapshots

**Comment by guigrpa** [comment]
That's interesting! I managed to pull off the integration you're suggesting adding the following configuration to the RN project's `package.json` (current Jest version: 17.0.0):

```json
	"jest": {
		"preset": "jest-react-native",
		"moduleNameMapper": {
			"react-native": "<rootDir>/node_modules/react-native-web"
		},
		"snapshotSerializers": [
			"<rootDir>/node_modules/jest-html"
		]
	}
```

You'll need to add both `jest-html` and `react-native-web` to your dependencies. The current version of `react-native-web` (0.0.49) worked for me. In addition, for this to work you'll need version `15.4.0-rc.4` of `react` and `react-test-renderer`, due to [this issue](https://github.com/facebook/react/issues/7386).

**Caveats:** you'll no longer have the *official* Jest snapshots with Views, Texts, and the like, but rather whatever `react-native-web` converts them to. You'll also probably need to tweak your CSS to ensure HTML previews are meaningful.

If you explore this approach, please share your impressions!

**Comment by sibelius** [comment]
Tks for the help!

I will wait until React release 15.4.0 to test this

**Comment by guigrpa** [comment]
It should be just around the corner! ;)

**Comment by gaearon** [comment]
React 15.4.0 is [out today](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html).

**Comment by guigrpa** [comment]
@sibelius Had success with your RN integration?

**Comment by sibelius** [comment]
I have this error using this approach

`Cannot find module 'react/lib/findDOMNode' from 'index.js'`

this is a breaking change on react 15.4.0

I need to open an issue on react-native-web to fix this

**Comment by guigrpa** [comment]
I guess this is now outdated. Please reopen if needed
